services:
  db:
    image: mysql:8.0
    command:
      - --default-authentication-plugin=mysql_native_password
      - --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
